### ISSUE TITLE
[Feature] Please implement Send for PineconeError

### ISSUE THREAD

**Issue by ragyabraham** [pinecone-io/pinecone-rust-client#54]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing functionality

### Describe the feature

The fact that the error type `PineconeError` does not implement `Send` makes it very difficult to work with these APIs in a multi-threaded application. Even just trying to make consecutive pinecone calls in the same in context becomes challenging as you can see from the below compiler error

```shell
   = help: the trait `std::marker::Send` is not implemented for `(dyn StdError + 'static)`, which is required by `{async block@src/adaptors/pinecone/apis.rs:11:89: 29:6}: std::marker::Send`
note: future is not `Send` as this value is used across an await
  --> src/adaptors/pinecone/apis.rs:16:84
   |
13 |         if let Ok(index_list) = self.list_indexes().await {
   |                                 ------------------------- has type `std::result::Result<IndexList, PineconeError>` which is not `Send`
...
16 |                     if let Ok(mut index) = self.index(index.name.as_str()).await {
   |                                                                                    ^^^^^ await occurs here, with `self.list_indexes().await` maybe used later
```.

### Describe alternatives you've considered

You have to call `unwrap` on the error

### Who will this benefit?

_No response_

### Are you interested in contributing this feature?

yes

### Anything else?

It would also be great if you could implement `Clone` for `PineconeError`. Would make it a lot easier to work with

**Comment by ragyabraham** [comment]
@jhamon @spacejam @iamannamai @emily-emily This actually makes it quite challenging to use the crate in a production setting. Is there anyway we can get this sorted or if there's a workaround

**Comment by austin-denoble** [comment]
@ragyabraham thanks for filing this enhancement. There's been a new version of the client published that hopefully satisfies the requirements here: https://github.com/pinecone-io/pinecone-rust-client/releases/tag/v0.1.2

Let us know if you're still running into issues.
